spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 21MB
      enabled: true
      file-size-threshold: 20MB
      resolve-lazily: true
  application:
    name: OlineMusicServer
  datasource:
    url: jdbc:mysql://localhost:3306/online_music?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      connect-timeout: 1800000
      lettuce:
        pool:
          max-active: 20
          max-wait: 1ms
          max-idle: 5
          min-idle: 0
server:
  port: 8888

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#阿里云
aliyun:
  oss:
    endPoint: 
    accessKeyId: 
    accessKeySecret: 
    bucketName: 
